language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
before_install:
  - npm config set registry http://registry.npmjs.org/
install:
  - npm install
after_script:
  - NODE_ENV=test npm run coverage && rm -rf ./coverage
