language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
install:
  - npm install
after_script:
  - NODE_ENV=test istanbul cover tap --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
